spring:
  application:
    name: tlias-web-management
  # mysql连接配置
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: '#123456'

# mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true # 开启驼峰命名法