spring:
  application:
    name: springboot-mybatis
  # 数据库连接信息
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/student
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '#123456'

# mybatis相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml